name: PR tests

on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: Swatinem/rust-cache@v2
      - name: Crate Format
        run: cargo fmt --check
      - name: Crate Check
        run: cargo check
      - name: Crate Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Crate Test
        run: cargo test
